[2025-02-28T17:36:22.980+0000] {processor.py:186} INFO - Started process (PID=12040) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:36:22.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:36:22.989+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:36:22.988+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:36:23.043+0000] {processor.py:925} INFO - DAG(s) 'etl_postgres_to_parquet' retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:36:23.212+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:36:23.211+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-28T17:36:23.243+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:36:23.242+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_postgres_to_parquet to 2025-02-28 00:00:00+00:00, run_after=2025-03-01 00:00:00+00:00
[2025-02-28T17:36:23.289+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.327 seconds
[2025-02-28T17:36:53.496+0000] {processor.py:186} INFO - Started process (PID=12346) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:36:53.498+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:36:53.501+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:36:53.500+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:36:53.527+0000] {processor.py:925} INFO - DAG(s) 'etl_postgres_to_parquet' retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:36:53.550+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:36:53.550+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-28T17:36:53.580+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:36:53.579+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_postgres_to_parquet to 2025-02-28 00:00:00+00:00, run_after=2025-03-01 00:00:00+00:00
[2025-02-28T17:36:53.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.136 seconds
[2025-02-28T17:37:23.743+0000] {processor.py:186} INFO - Started process (PID=12652) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:37:23.744+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:37:23.747+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:37:23.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:37:23.770+0000] {processor.py:925} INFO - DAG(s) 'etl_postgres_to_parquet' retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:37:23.788+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:37:23.788+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-28T17:37:23.823+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:37:23.823+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_postgres_to_parquet to 2025-02-28 00:00:00+00:00, run_after=2025-03-01 00:00:00+00:00
[2025-02-28T17:37:23.850+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.117 seconds
[2025-02-28T17:37:54.089+0000] {processor.py:186} INFO - Started process (PID=12958) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:37:54.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:37:54.093+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:37:54.093+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:37:54.118+0000] {processor.py:925} INFO - DAG(s) 'etl_postgres_to_parquet' retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:37:54.266+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:37:54.265+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-28T17:37:54.309+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:37:54.308+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_postgres_to_parquet to 2025-02-28 00:00:00+00:00, run_after=2025-03-01 00:00:00+00:00
[2025-02-28T17:37:54.339+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.258 seconds
[2025-02-28T17:38:24.605+0000] {processor.py:186} INFO - Started process (PID=13264) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:38:24.607+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:38:24.611+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:38:24.610+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:38:24.644+0000] {processor.py:925} INFO - DAG(s) 'etl_postgres_to_parquet' retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:38:24.685+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:38:24.685+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-28T17:38:24.728+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:38:24.728+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_postgres_to_parquet to 2025-02-28 00:00:00+00:00, run_after=2025-03-01 00:00:00+00:00
[2025-02-28T17:38:24.767+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.175 seconds
[2025-02-28T17:38:55.396+0000] {processor.py:186} INFO - Started process (PID=13570) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:38:55.397+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:38:55.400+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:38:55.400+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:38:55.428+0000] {processor.py:925} INFO - DAG(s) 'etl_postgres_to_parquet' retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:38:55.441+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:38:55.441+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-28T17:38:55.476+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:38:55.476+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_postgres_to_parquet to 2025-02-28 00:00:00+00:00, run_after=2025-03-01 00:00:00+00:00
[2025-02-28T17:38:55.504+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.117 seconds
[2025-02-28T17:39:26.034+0000] {processor.py:186} INFO - Started process (PID=13876) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:39:26.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:39:26.039+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:39:26.039+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:39:26.068+0000] {processor.py:925} INFO - DAG(s) 'etl_postgres_to_parquet' retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:39:26.240+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:39:26.239+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-28T17:39:26.287+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:39:26.286+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_postgres_to_parquet to 2025-02-28 00:00:00+00:00, run_after=2025-03-01 00:00:00+00:00
[2025-02-28T17:39:26.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.300 seconds
[2025-02-28T17:39:56.627+0000] {processor.py:186} INFO - Started process (PID=14185) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:39:56.629+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:39:56.632+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:39:56.631+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:39:56.660+0000] {processor.py:925} INFO - DAG(s) 'etl_postgres_to_parquet' retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:39:56.684+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:39:56.684+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-28T17:39:56.717+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:39:56.716+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_postgres_to_parquet to 2025-02-28 00:00:00+00:00, run_after=2025-03-01 00:00:00+00:00
[2025-02-28T17:39:56.743+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.126 seconds
[2025-02-28T17:40:26.998+0000] {processor.py:186} INFO - Started process (PID=14482) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:40:26.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:40:27.002+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:40:27.002+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:40:27.043+0000] {processor.py:925} INFO - DAG(s) 'etl_postgres_to_parquet' retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:40:27.064+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:40:27.063+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-28T17:40:27.096+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:40:27.096+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_postgres_to_parquet to 2025-02-28 00:00:00+00:00, run_after=2025-03-01 00:00:00+00:00
[2025-02-28T17:40:27.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.135 seconds
[2025-02-28T17:40:58.014+0000] {processor.py:186} INFO - Started process (PID=14785) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:40:58.015+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:40:58.018+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:40:58.017+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:40:58.047+0000] {processor.py:925} INFO - DAG(s) 'etl_postgres_to_parquet' retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:40:58.190+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:40:58.190+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-28T17:40:58.220+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:40:58.220+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_postgres_to_parquet to 2025-02-28 00:00:00+00:00, run_after=2025-03-01 00:00:00+00:00
[2025-02-28T17:40:58.260+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.253 seconds
[2025-02-28T17:41:28.988+0000] {processor.py:186} INFO - Started process (PID=15091) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:41:28.990+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:41:28.996+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:41:28.995+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:41:29.034+0000] {processor.py:925} INFO - DAG(s) 'etl_postgres_to_parquet' retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:41:29.066+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:41:29.066+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-28T17:41:29.105+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:41:29.105+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_postgres_to_parquet to 2025-02-28 00:00:00+00:00, run_after=2025-03-01 00:00:00+00:00
[2025-02-28T17:41:29.151+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.170 seconds
[2025-02-28T17:41:59.879+0000] {processor.py:186} INFO - Started process (PID=15397) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:41:59.881+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:41:59.884+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:41:59.884+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:41:59.913+0000] {processor.py:925} INFO - DAG(s) 'etl_postgres_to_parquet' retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:41:59.931+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:41:59.930+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-28T17:41:59.970+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:41:59.970+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_postgres_to_parquet to 2025-02-28 00:00:00+00:00, run_after=2025-03-01 00:00:00+00:00
[2025-02-28T17:42:00.000+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.128 seconds
[2025-02-28T17:42:12.058+0000] {processor.py:186} INFO - Started process (PID=15437) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:42:12.059+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:42:12.064+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:42:12.063+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:42:12.108+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:42:12.102+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_process_to_parquet_ha.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_process_to_parquet_ha.py", line 200, in <module>
    'start_date': datetime(2024, 2, 27),
                  ^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable. Did you mean: 'datetime.datetime(...)'?
[2025-02-28T17:42:12.110+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:42:12.141+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.090 seconds
[2025-02-28T17:43:19.239+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:43:19.240+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:43:19.242+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:43:19.242+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:43:19.259+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:43:19.255+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_process_to_parquet_ha.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_process_to_parquet_ha.py", line 200, in <module>
    'start_date': datetime(2024, 2, 27),
                  ^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable. Did you mean: 'datetime.datetime(...)'?
[2025-02-28T17:43:19.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:43:19.285+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.053 seconds
[2025-02-28T17:43:49.870+0000] {processor.py:186} INFO - Started process (PID=495) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:43:49.872+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:43:49.875+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:43:49.875+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:43:49.898+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:43:49.894+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_process_to_parquet_ha.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_process_to_parquet_ha.py", line 200, in <module>
    'start_date': datetime(2024, 2, 27),
                  ^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable. Did you mean: 'datetime.datetime(...)'?
[2025-02-28T17:43:49.900+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:43:49.936+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.073 seconds
[2025-02-28T17:44:20.194+0000] {processor.py:186} INFO - Started process (PID=801) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:44:20.196+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:44:20.200+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:44:20.199+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:44:20.233+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:44:20.225+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_process_to_parquet_ha.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_process_to_parquet_ha.py", line 200, in <module>
    'start_date': datetime(2024, 2, 27),
                  ^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable. Did you mean: 'datetime.datetime(...)'?
[2025-02-28T17:44:20.236+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:44:20.267+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.081 seconds
[2025-02-28T17:44:50.584+0000] {processor.py:186} INFO - Started process (PID=1107) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:44:50.585+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:44:50.589+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:44:50.588+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:44:50.611+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:44:50.606+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_process_to_parquet_ha.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_process_to_parquet_ha.py", line 200, in <module>
    'start_date': datetime(2024, 2, 27),
                  ^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable. Did you mean: 'datetime.datetime(...)'?
[2025-02-28T17:44:50.613+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:44:50.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.071 seconds
[2025-02-28T17:45:20.822+0000] {processor.py:186} INFO - Started process (PID=1413) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:45:20.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:45:20.827+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:45:20.826+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:45:20.846+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:45:20.842+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_process_to_parquet_ha.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_process_to_parquet_ha.py", line 200, in <module>
    'start_date': datetime(2024, 2, 27),
                  ^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable. Did you mean: 'datetime.datetime(...)'?
[2025-02-28T17:45:20.848+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:45:20.893+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.080 seconds
[2025-02-28T17:45:50.977+0000] {processor.py:186} INFO - Started process (PID=1719) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:45:50.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:45:50.981+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:45:50.981+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:45:51.000+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:45:50.995+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_process_to_parquet_ha.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_process_to_parquet_ha.py", line 200, in <module>
    'start_date': datetime(2024, 2, 27),
                  ^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable. Did you mean: 'datetime.datetime(...)'?
[2025-02-28T17:45:51.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:45:51.029+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.059 seconds
[2025-02-28T17:46:22.030+0000] {processor.py:186} INFO - Started process (PID=2031) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:46:22.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:46:22.035+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:46:22.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:46:22.069+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:46:22.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_process_to_parquet_ha.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_process_to_parquet_ha.py", line 200, in <module>
    'start_date': datetime(2024, 2, 27),
                  ^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable. Did you mean: 'datetime.datetime(...)'?
[2025-02-28T17:46:22.073+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:46:22.119+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.105 seconds
[2025-02-28T17:46:23.465+0000] {processor.py:186} INFO - Started process (PID=2056) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:46:23.467+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:46:23.472+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:46:23.471+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:46:23.515+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:46:23.510+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_process_to_parquet_ha.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_process_to_parquet_ha.py", line 200, in <module>
    'start_date': datetime(2024, 2, 27),
                  ^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable. Did you mean: 'datetime.datetime(...)'?
[2025-02-28T17:46:23.517+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:46:23.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.104 seconds
[2025-02-28T17:46:54.448+0000] {processor.py:186} INFO - Started process (PID=2362) to work on /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:46:54.450+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_process_to_parquet_ha.py for tasks to queue
[2025-02-28T17:46:54.452+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:46:54.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:46:54.469+0000] {logging_mixin.py:190} INFO - [2025-02-28T17:46:54.465+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_process_to_parquet_ha.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_process_to_parquet_ha.py", line 200, in <module>
    'start_date': datetime(2024, 2, 27),
                  ^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable. Did you mean: 'datetime.datetime(...)'?
[2025-02-28T17:46:54.471+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_process_to_parquet_ha.py
[2025-02-28T17:46:54.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_process_to_parquet_ha.py took 0.056 seconds
